version: '3'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "4000:4000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:5001  

  backend:
    build:
      context: ./backend
    ports:
      - "5001:5000"
    depends_on:
      - mysql
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: casaroes_db
    volumes:
      - backend-data:/app

  mysql:
    image: mysql:latest
    ports:
      - "3307:3306"  
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: casaroes_db
    volumes:
      - mysql-data:/var/lib/mysql

  sonarqube:
    image: sonarqube:community
    ports:
      - "9000:9000" # Porta padrão do SonarQube
    depends_on:
      - sonarqube-db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonarqube-db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube-data:/opt/sonarqube/data
      - sonarqube-extensions:/opt/sonarqube/extensions
      - sonarqube-logs:/opt/sonarqube/logs

  sonarqube-db:
    image: postgres:14
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  backend-data:
  mysql-data:
  sonarqube-data:
  sonarqube-extensions:
  sonarqube-logs:
  postgres-data:
